spring:
  #Embedded database configuration
  h2:
    console:
      enabled: true #enables web console in browser for h2
  datasource:
    url: jdbc:h2:mem:testdb #Sets db url to connect
#logging:
 # level: 
  #  root: debug #Sets log level to debug to see all "auto-configurarion report"