/**
 * When using embedded DB schema is autogenerated by hibernate
 */
/*
CREATE TABLE person(
	id INTEGER NOT NULL,
	name VARCHAR(255) NOT NULL,
	location VARCHAR(255),
	birth_date TIMESTAMP,
	PRIMARY KEY(id)
);*/

/*
INSERT INTO person (id,name,location,birth_date) values (10001,'Homs','Mexico',CURRENT_TIMESTAMP());
INSERT INTO person (id,name,location,birth_date) values (10002,'Marina','Mexico',CURRENT_TIMESTAMP());
INSERT INTO person (id,name,location,birth_date) values (10003,'Kayle','Mexico',CURRENT_TIMESTAMP());
*/

INSERT INTO course (id,name,created_at,updated_at) values (10001,'JPA in 100 steps',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO course (id,name,created_at,updated_at) values (10002,'Java in 100 steps',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO course (id,name,created_at,updated_at) values (10003,'Maven in 100 steps',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());

INSERT INTO passport (id,number) values (40001,'P01234');
INSERT INTO passport (id,number) values (40002,'P01235');
INSERT INTO passport (id,number) values (40003,'P01236');

INSERT INTO student (id,name,passport_id) values (20001,'Homs',40001);
INSERT INTO student (id,name,passport_id) values (20002,'Marina',40002);
INSERT INTO student (id,name,passport_id) values (20003,'Kayle',40003);

INSERT INTO review (id,rating,description,course_id) values (50001,5,'Cool',10001);
INSERT INTO review (id,rating,description,course_id) values (50002,5,'Great',10001);
INSERT INTO review (id,rating,description,course_id) values (50003,5,'Amazing',10002);

/*
INSERT INTO student_course(student_id,course_id) values (10001,20001);
INSERT INTO student_course(student_id,course_id) values (10001,20002);
INSERT INTO student_course(student_id,course_id) values (10002,20003);
*/
